[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'solady/=lib/solady/src/utils/',
    '@chimera/=lib/chimera/src/'
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/kOTtPAuW53tAOR-uX27jHdhkLMh2JwcV"
